# Generated by Django 4.2.14 on 2024-07-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=50, verbose_name='category name')),
                ('CatImg', models.ImageField(upload_to='media/categroy_image', verbose_name='category image')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(max_length=50, verbose_name='product name')),
                ('ProImg', models.ImageField(upload_to='media/product_image', verbose_name='product image')),
                ('ProDesc', models.TextField(verbose_name='product description')),
                ('ProPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product proce')),
                ('ProQua', models.IntegerField(verbose_name='product quantity')),
                ('ProCatg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='product category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
