# Generated by Django 4.2.14 on 2024-07-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProSale',
            field=models.IntegerField(default=0, verbose_name='sales'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProDesc',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProQua',
            field=models.IntegerField(verbose_name='quantity'),
        ),
    ]
