# Generated by Django 4.2.14 on 2024-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_prosale_alter_product_prodesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PkName', models.CharField(max_length=50, verbose_name='product name')),
                ('PkImg', models.ImageField(upload_to='media/product_image', verbose_name='product image')),
                ('PkDesc', models.TextField(verbose_name='description')),
                ('PkPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('PkSale', models.IntegerField(default=0, verbose_name='sales')),
                ('Pkcontent', models.ManyToManyField(to='core.product', verbose_name='contents')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
