# Generated by Django 4.2.9 on 2024-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrName', models.CharField(max_length=50, verbose_name='customer name')),
                ('CrJob', models.CharField(max_length=50, verbose_name='job')),
                ('CrImg', models.ImageField(upload_to='media/customer_photo', verbose_name='photo')),
                ('CrReview', models.TextField(verbose_name='customer review')),
                ('Crshow', models.BooleanField(verbose_name='put in the website')),
            ],
            options={
                'verbose_name': 'Customer_review',
                'verbose_name_plural': 'Customer_reviews',
            },
        ),
        migrations.AlterField(
            model_name='package',
            name='PkImg',
            field=models.ImageField(upload_to='media/package_image', verbose_name='product image'),
        ),
    ]
