# Generated by Django 4.2.9 on 2024-07-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_review_alter_package_pkimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_review',
            old_name='Crshow',
            new_name='CrShow',
        ),
    ]
