# Generated by Django 4.2.14 on 2024-07-23 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_rename_crshow_customer_review_crshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CtQuantity', models.PositiveIntegerField(default=1)),
                ('CtCreated_at', models.DateTimeField(auto_now_add=True)),
                ('CtUpdated_at', models.DateTimeField(auto_now=True)),
                ('CtProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('CtUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
