# Generated by Django 4.2.14 on 2024-07-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cartcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CtUser',
        ),
        migrations.DeleteModel(
            name='CartCounter',
        ),
    ]
