# Generated by Django 4.2.14 on 2024-07-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cart_session_key_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CtProduct',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='CtQuantity',
        ),
    ]
