# Generated by Django 4.2.14 on 2024-07-26 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_cart_ctproduct_remove_cart_ctquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='CiCart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_at',
            new_name='CiCreated_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='CiProduct',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='CiQuantity',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='updated_at',
            new_name='CiUpdated_at',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='PkSale',
            new_name='PkClicks',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProSale',
        ),
        migrations.AddField(
            model_name='package',
            name='PkCreated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='ProClicks',
            field=models.IntegerField(default=0, verbose_name='number of clicks(product populer)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProCreated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
