# Generated by Django 4.2.14 on 2024-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_cart_cartitem_cicart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='package',
            name='Pkcontent',
        ),
        migrations.AlterField(
            model_name='product',
            name='ProClicks',
            field=models.IntegerField(default=0, verbose_name='number of clicks (populer)'),
        ),
    ]
