# Generated by Django 4.2.14 on 2024-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customer_review_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='PkContent',
            field=models.ManyToManyField(to='core.product', verbose_name='contents'),
        ),
    ]
