# Generated by Django 4.2.14 on 2024-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_package_pkcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='PkSlug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProSlug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
