# Generated by Django 4.2.14 on 2024-07-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_package_pkslug_product_proslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='PkSlug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name="leav it..! (do't change it)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProSlug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name="leav it..! (do't change it)"),
        ),
    ]
