# Generated by Django 4.2.14 on 2024-07-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_package_pkslug_alter_product_proslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='CiPackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.package'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='CiProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
