# Generated by Django 4.2.14 on 2024-07-31 10:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cartitem_cipackage_alter_cartitem_ciproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='PkSlug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='Package-djangodbmodelsfieldscharfield', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProSlug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='product-djangodbmodelsfieldscharfield', unique=True),
        ),
    ]
