# Generated by Django 4.2.14 on 2024-07-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_package_pkslug_alter_product_proslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='PkSlug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProSlug',
        ),
    ]
