# Generated by Django 4.2.14 on 2024-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_package_pkslug_remove_product_proslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdName', models.CharField(max_length=50, verbose_name='name(this will be showing in the page)')),
                ('AdImg', models.ImageField(upload_to='media/<django.db.models.fields.CharField>', verbose_name='img')),
            ],
        ),
    ]
