# Generated by Django 4.2.14 on 2024-08-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='AdImg',
            field=models.ImageField(upload_to='media/additiona', verbose_name='img'),
        ),
    ]
