# Generated by Django 4.2.14 on 2024-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_additional_adimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='Adimgur_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Catimgur_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='Crimgur_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='Pkimgur_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Proimgur_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
