# Generated by Django 4.2.14 on 2024-08-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_additional_adimgur_url_category_catimgur_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='AdImg',
            field=models.ImageField(upload_to='addtional_image', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatImg',
            field=models.ImageField(upload_to='category_image', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='CrImg',
            field=models.ImageField(upload_to='customer_photo', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='package',
            name='PkImg',
            field=models.ImageField(upload_to='package_image', verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProImg',
            field=models.ImageField(upload_to='product_image', verbose_name='product image'),
        ),
    ]
