# Generated by Django 4.2.14 on 2024-08-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_additional_adimg_alter_category_catimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Proimgur_url',
            new_name='Proflickr_url',
        ),
    ]
