# Generated by Django 4.2.14 on 2024-08-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_proimgur_url_product_proflickr_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Proflickr_url',
            new_name='Proimg_url',
        ),
    ]
