# Generated by Django 4.2.14 on 2024-08-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_proflickr_url_product_proimg_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional',
            options={'verbose_name': 'صفحت', 'verbose_name_plural': 'صفحات اضافية (الجديد و الشائعة)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'قسم', 'verbose_name_plural': 'الاقسام'},
        ),
        migrations.AlterModelOptions(
            name='customer_review',
            options={'verbose_name': 'مراجعة عميل', 'verbose_name_plural': 'مراجعة العملاء'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'حقية', 'verbose_name_plural': 'حقائب جاهزة'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.RemoveField(
            model_name='additional',
            name='Adimgur_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Catimgur_url',
        ),
        migrations.RemoveField(
            model_name='customer_review',
            name='Crimgur_url',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Pkimgur_url',
        ),
        migrations.AddField(
            model_name='additional',
            name='Adimg_url',
            field=models.URLField(blank=True, null=True, verbose_name='صورة عبر الانترنت'),
        ),
        migrations.AddField(
            model_name='category',
            name='Catimg_url',
            field=models.URLField(blank=True, null=True, verbose_name='اضافة صورة من الانترنت'),
        ),
        migrations.AddField(
            model_name='package',
            name='Pkimg_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة عبر الانترنت'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='AdImg',
            field=models.ImageField(upload_to='addtional_image', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='AdName',
            field=models.CharField(max_length=50, verbose_name='اسم الصفحة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatImg',
            field=models.ImageField(upload_to='category_image', verbose_name='صورة القسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatName',
            field=models.CharField(max_length=50, verbose_name='اسم القسم'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='CrImg',
            field=models.ImageField(upload_to='customer_photo', verbose_name='صورة العميل'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='CrJob',
            field=models.CharField(max_length=50, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='CrName',
            field=models.CharField(max_length=50, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='CrReview',
            field=models.TextField(verbose_name='مراجعة العميل'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='CrShow',
            field=models.BooleanField(verbose_name='اضافة الى الموقع\n(يجب اختيار اكثر من 3)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='PkClicks',
            field=models.IntegerField(default=0, verbose_name='عدد الضغطات (يحدد شعبية المنتج)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='PkContent',
            field=models.ManyToManyField(to='core.product', verbose_name='محتويات الحقيبة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='PkDesc',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='package',
            name='PkImg',
            field=models.ImageField(blank=True, null=True, upload_to='package_image', verbose_name='صورة محلية'),
        ),
        migrations.AlterField(
            model_name='package',
            name='PkName',
            field=models.CharField(max_length=50, verbose_name='اسم الحقيبة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='PkPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='السعر (لن يظهر السعر في الموقع)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProCatg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProClicks',
            field=models.IntegerField(default=0, verbose_name='عدد الضغطات (يحدد شعبية المنتج)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProDesc',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProImg',
            field=models.ImageField(blank=True, null=True, upload_to='product_image', verbose_name='صورة محلية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProName',
            field=models.CharField(max_length=50, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='السعر (لن يظهر السعر في الموقع)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Proimg_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة'),
        ),
    ]
