# Generated by Django 4.2.14 on 2024-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_additional_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='AdImg',
            field=models.ImageField(blank=True, null=True, upload_to='addtional_image', verbose_name='الصورة'),
        ),
    ]
