# Generated by Django 4.2.14 on 2024-08-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_additional_adimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_message', models.TextField(verbose_name='رائس الرسالة')),
                ('footer_message', models.TextField(verbose_name='ذيل الرسالة')),
            ],
            options={
                'verbose_name': 'رسالة الوتس',
                'verbose_name_plural': 'رسائل الوتس',
            },
        ),
    ]
